theme: jekyll-theme-minimal
title: Yue 'Luna' Huang
description: Leverage Economics and Data Science Tools to Tackle International Development Challenges

baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-115019672-1
