theme: jekyll-theme-minimal

title: Yue 'Luna' Huang
short_description: Ph.D. Student at UC Berkeley
long_description: Harness Advances in Econometrics and Data Sciences to Improve Lives of the Poor

profile_pic: /img/profile.jpg
cv_file: /pdf/cv.pdf

url: "luna983.github.io"
long_url: "https://luna983.github.io"

google_analytics: UA-115019672-1
